### ISSUE TITLE
I got the keyerror when runing the test

### ISSUE THREAD

**Issue by Eucliwoodprpr** [microsoft/CoCosNet-v2#10]
when I run the test, I got the keyerror results.
python test.py --name deepfashionHD --dataset_mode deepfashionHD --dataroot deepfashionHD --PONO --PONO_C --no_flip --batchSize 8 --gpu_ids 0 --netCorr NoVGGHPM --nThreads 16 --nef 32 --amp --display_winsize 512 --iteration_count 5 --load_size 512 --crop_size 512

<img width="809" alt="スクリーンショット 2021-08-16 214214" src="https://user-images.githubusercontent.com/88889979/129565547-511f60a4-e792-4b23-ac82-3928ff8922bc.png">
(the images have been resized to 512)

**Comment by zhruifen** [comment]
Hi Did you solve this problem? I run into the same issue.

**Comment by Eucliwoodprpr** [comment]
> Hi Did you solve this problem? I run into the same issue.
no, I have no idea.

**Comment by jkxing** [comment]
It's the problem of '/' and '\\', you need to unify them
