### ISSUE TITLE
train Metfaces dataset error

### ISSUE THREAD

**Issue by JcccKing** [microsoft/CoCosNet-v2#24]
Hello friends, I use your model to train metfaces dataset and create paired label edge label After 100 rounds of training, classify the pictures according to the cosine similarity of VGG extracted features. The test results are as follows. What's the problem? Thank you and wish you success in your scientific research!
![image](https://user-images.githubusercontent.com/46700363/151274059-a7a6a023-e7ff-470b-a662-fb9dcc5ea349.png)
![image](https://user-images.githubusercontent.com/46700363/151274181-42a5a7e3-7a82-4794-86a5-7dddbd6d455a.png)

**Comment by SystemErrorWang** [comment]
hello JcccKing, do you have any update about this problem? I am facing the same problem and would like to know the reason

**Comment by JcccKing** [comment]
Hello
I have solved part of the problem, but it does not reproduce the generalization effect in the paper completely.
My solution is as follows
1. First of all, we need to align the images, VGG calculate the similarity between external images and sample images, and choose the one with high similarity to generate. Try to avoid side faces and gender differences.
2. You can refer to my paper(https://github.com/AiArt-HDU/MATEBIT), I subsequently improved v2; to improve the generalization of certain external data.
